errorTypes = {
    "HTTP_ERROR": "HTTP_ERROR",
    "HTTP_CONNECTION_ERROR": "HTTP_CONNECTION_ERROR",
    "INTERNAL_SERVER_ERROR": "INTERNAL_SERVER_ERROR",
    "UNPROCESSABLE_ENTITY": "UNPROCESSABLE_ENTITY",
    "VALIDATION_FAILED": "VALIDATION_FAILED",
    "OPERATION_FORBIDDEN": "OPERATION_FORBIDDEN",
    "NOT_FOUND_ERROR": "NOT_FOUND_ERROR",
    "UNAUTHORIZED_ACCESS": "UNAUTHORIZED_ACCESS",
    "BAD_REQUEST": "BAD_REQUEST",
    "SERVICE_UNAVAILABLE": "SERVICE_UNAVAILABLE",
    "DUPLICATE_RESOURCE": "DUPLICATE_RESOURCE",
    "MISSING_FIELD": "MISSING_FIELD",
    "RATE_LIMIT_EXCEEDED": "RATE_LIMIT_EXCEEDED",
    "DATABASE_COMMIT_ERROR": "DATABASE_COMMIT_ERROR"
}


statusCodes = {
    "200": 200,
    "201": 201,
    "400": 400,
    "401": 401,
    "403": 403,
    "404": 404,
    "422": 422,
    "429": 429,
    "500": 500,
    "503": 503
}